### PR TITLE
Hec payload event dedup

### PR DESCRIPTION
**Pull request by jettero**

### CODE REVIEW

**Comment by basepi** [comment]
@sumanmehta FYI. This will change some field names in splunk, but for the better. Apparently splunk *really* doesn't like fields duplicated in both the event and the payload. This will rename any duplicates in the even to `<old_name>_meta`.

**Comment by sumanmehta** [comment]
@basepi Thanks for informing. This change does not seem to impact any of our dashboards or ticketing workflows.

**Comment by yassingh** [comment]
@basepi 
@jettero 
two more questions in order to better analyze the impact:
Q. Have you seen this conflict/duplicity arising somewhere? Or is it just a precautionary change?
Q. If you have seen this duplicity somewhere, please tell me its "sourcetype" or what kind of hubble log it is ( just want to be sure that any of our existing splunk queries do not break )

On a cursory review, I could not find any existing splunk logs which would be affected.

**Comment by basepi** [comment]
I'll let @fossam comment, as he's the one who has been working with the splunk team, and I don't know the underlying details.

**Pull request merged**
