### PR TITLE
Log config to Splunk on startup (4)

### PR DESCRIPTION
**Pull request by mew1033**

### CODE REVIEW

**Review by jettero — APPROVED** [review]

**Review by fossam — APPROVED** [review]

**Comment by fossam** [comment]
@mew1033, does this change needs to be made also on 3.x branch?

**Comment by jettero** [comment]
@fossam there was a separate PR for that I think

**Comment by fossam** [comment]
@jettero apologies, i didn't find it earlier and they weren't linked.

**Comment by fossam** [comment]
Related pr against 3.0 branch is #931 .

**Comment by fossam** [comment]
@mew1033 did this change give the expected result you're after during test?

**Comment by fossam** [comment]
Would it make sense and be cleaner to emit initial grains and config items after single function run ?

**Pull request merged**
