### PR TITLE
from hubblestack.extmods.fdg.process import encode_base64 issues …

### PR DESCRIPTION
**Pull request by jettero**
from hubblestack.extmods.fdg.process import encode_base64 is fine if you're
running a source install but if the live readfile.py is in /var/cache, this
causes an import problem.

Let's try using local import from process (which should be near to readfile.py
either in /var/cache or in $LIBDIR/hubblestack/extmods/fdg

### CODE REVIEW

**Comment by jettero** [comment]
I think this addresses the immediate problem, but it'd probably better to create a utility function that we can import with absolute import.

**Comment by basepi** [comment]
Yeah I would probably make something in hubblestack.utils that does the functionality, and have both process.py and readfile.py import that util. Cleaner and more explicit.

**Comment by jettero** [comment]
I'm inclined to leave this is a temporary fix so I can hurry and get it into 3.0.7 though. That's apparently pretty rushed at the moment.

**Comment by Tenebriso** [comment]
That look great and clean, nice! I think we need to change the unittests as well since we moved the function they are going to fail, maybe move the ones for encode_base64 from test_process.py to a test_encoding.py?

**Comment by jettero** [comment]
> I think we need to change the unittests as well since we moved the function …

Well, I moved it, but I also kept it there. I wouldn't think it'd make much difference for the tests. Possibly we need a new test_encoding set, but it'd be the same-ish, no?

Oh, I see the problem. forgot to import logging. Good job tests! \o/

**Pull request merged**
