### PR TITLE
Add fallback to fileserver in case of no default gateway

### PR DESCRIPTION
**Pull request by basepi**

### CODE REVIEW

**Comment by fossam** [comment]
If there's one thing, can the `python_shell=True` be avoided in #285 ?

**Comment by basepi** [comment]
@fossam Maybe. But it's not relevant to this PR, and not necessary in any case, as it doesn't use user input, so is not a command injection vulnerability.

**Comment by fossam** [comment]
You're correct, I just wanted to avoid shelling out since it was easily avoidable in this case. Sorry to derail conversation in this PR.

To help us get back on the subject - what happens in case there is no default gateway but a configured fileserver is reachable regardless?

**Comment by basepi** [comment]
It will fall back. Which I think is fine for this stop-gap solution -- see the conversation over [here](https://github.com/hubblestack/hubble/pull/285) where other solutions were discussed. We should probably implement a more targeted solution in the future, but with the looming release I think we should stick with this for now.

**Comment by sumanmehta** [comment]
Does the token remain same for fallback_indexer? Do you not need a fallback_token as well?

**Comment by basepi** [comment]
For DMa, the auth information is the same. It's just whether we use internal DNS or external DNS. One resolves, the other doesn't, for these hosts.

We could add alternate auth as an option if your team would like to use it.

**Comment by sumanmehta** [comment]
ok. PR looks fine to me.

**Pull request merged**
