### PR TITLE
Adding exception handling in running schedules

### PR DESCRIPTION
**Pull request by devagupt**
- Currently if a schedule gets an exception it leads to subsequent schedules not running. Fixed this behaviour by adding exception handling while running schedules so that if an exception occurs in running a schedule, it gets logged and next schedule gets picked up.

### CODE REVIEW

**Comment by jettero** [comment]
I've never noticed this behavior. I'm going to want to try to reproduce.

**Comment by MoodyMudit** [comment]
We might not plan to release any more 3.0 builds. Let's make sure that this change is merged into develop and 4.0 branch as well.

**Comment by devagupt** [comment]
> make

Will create a sepafrate PR for merging in develop branch as well.

**Comment by jettero** [comment]
Please don't merge things into develop. We're trying to finish up 4.0 to merge to develop, that will just cause conflicts.

**Comment by jettero** [comment]
I would say that we shouldn't merge this into 3.0 at all (except that it's clearly ready to go). The next release will be 4.0 so we should probably only merge it there.

**Pull request merged**
