### PR TITLE
conflicts resolved 

### PR DESCRIPTION
**Pull request by jettero**
I tried to update the #711  PR, but couldn't figure it out. This is my conflict resolution for it...

### CODE REVIEW

**Comment by jettero** [comment]
@praksinha let's merge this and close your merge forward...

I'm just waiting on an approval. Or we could merge this into yours and merge that. I'm fine either way.

**Comment by praksinha** [comment]
@jettero @Tenebriso It seems this PR is overriding changes from PR #684 .
Is it fine ?

**Comment by jettero** [comment]
> @jettero @Tenebriso It seems this PR is overriding changes from PR #684 .
> Is it fine ?

Where specifically? There were a lot of conflicts. I tried really hard to preserve the intent of the things I was merging, but at least one was really confusing.

**Comment by praksinha** [comment]
> > @jettero @Tenebriso It seems this PR is overriding changes from PR #684 .
> > Is it fine ?
> 
> Where specifically? There were a lot of conflicts. I tried really hard to preserve the intent of the things I was merging, but at least one was really confusing.

Example: Changes like https://github.com/hubblestack/hubble/pull/713/files#diff-8618449a693ddafd0882b7564ee2212fL10 and fdg.py line 126

**Comment by jettero** [comment]
Oh, I see the problem. Yeah. logger instances should be called log, even though they're normally globals. This is something we should change in the pylintrc rather than changing the names of the logger to LOG.

**Pull request merged**
