### PR TITLE
update Dockerfiles to osquery 2.7.0 

### PR DESCRIPTION
**Pull request by fossam**
These commits aim to bring osquery 2.7.0 to Hubble packages. Only the build process has been tested.
When using these changes to build packages note:

0. docker pull <distro_image> before the build to have the latest as a starting point
1. Hubble develop branch is used for checkout in the Dockerfiles (v2.2.3 -> develop)
2. Hubble version was left 2.2.3 for package names.

### CODE REVIEW

**Comment by basepi** [comment]
It's conflicting. Can you rebase?

**Comment by fossam** [comment]
Why does it say it dismissed? I didn't dismiss anything.

**Comment by fossam** [comment]
Now all of the Dockerfiles are in and now the original PR was to be merged. I'd love to have a button to block a PR until it's ready. But I guess I could have not done PR in the first place.

**Comment by basepi** [comment]
When new commits are pushed, previous reviews are dismissed.

**Comment by basepi** [comment]
The button to block a PR is to leave a comment saying "please don't merge this until I say it's read." Or a WIP in the title or something. :)

**Comment by basepi** [comment]
(BTW this is still conflicting, needs a rebase or a from upstream/develop)

**Pull request merged**
