### PR TITLE
Convert Vulners scanner to use SDK

### LINKED ISSUE #438: Vulners Python API support
Hi fellows!
May I suggest you refactoring Vulners Scanner to the public [Vulners Python API](https://github.com/vulnersCom/api).
It's completely supported and I think will make it easier to integrate.
It's also [available via Pypi](https://pypi.org/project/vulners/).

### PR DESCRIPTION
**Pull request by NerdsvilleCEO**
Resolves #438

### CODE REVIEW

**Comment by basepi** [comment]
Sorry for my late reply here, I was out of the office (and out of cell service) for awhile.

This looks good -- can you please just add the vulners library to each of the pyinstaller-requirements.txt files inside of the `pkg` directory? As well as in the setup.py as well? That way our docker-built packages will include it, as will any source installs (that don't use pip).

And while you're at it, can you add `salt-ssh` to your requirements.txt file? If we're going to add an explicit requirements file, I want it to be complete.

**Comment by NerdsvilleCEO** [comment]
@basepi I can definitely make these changes, I am re-setting up my development environment and can take care of this tomorrow at the latest

Thanks!

**Comment by basepi** [comment]
No hurry! I appreciate these changes!

**Comment by NerdsvilleCEO** [comment]
@basepi working on this now, had a quick question, is there a reason these all don't just share a single pyinstaller-requirements.txt?

**Comment by basepi** [comment]
Mostly because we don't want to mount `../<something>` in the dockerfile. With the way we mount now it can only see the local directory, so we copy it to each location. It changes infrequently enough that it hasn't been a huge issue, though it still is an ugly solution.

**Comment by NerdsvilleCEO** [comment]
@basepi could you please review the changes? Thanks!

**Comment by vulnersCom** [comment]
Hi fellows! That's a really nice work, thank you!
May I ask you not to set vulners == 1.3.0 version?
Please, use latest, I'm checking backport compatibility.
There is a lot of performance tuning in 1.3.5.

**Comment by NerdsvilleCEO** [comment]
I can make this change in a separate PR @vulnersCom thanks!

**Pull request merged**
