### PR TITLE
Merging latest fixes in Master branch

### PR DESCRIPTION
**Pull request by MoodyMudit**
The changes include
* Windows caching fix for file paths.
* Correcting **mode** value in stat_nova.
* adding more details in result of oval scanner.

### CODE REVIEW

**Review by sumanmehta — APPROVED** [review]

**Comment by jettero** [comment]
Wow, I had no idea we've been building docker images for every PR for the last dozen years.

That cent7dev.dockerfile is failing because of a missing pip repository? I have to assume it was a transient error. The link is broken...

https://hub.docker.com/repository/registry-1.docker.io/hubblestack/cent7dev/builds/033cfc9f-03c3-40ae-8ea0-4d24319209fa

**Comment by jettero** [comment]
There's no way that webhook has worked since like 2016 or worse. I don't understand why it's blocking PRs suddenly starting today... I deleted the webhook here and on dockerhub.

**Comment by MoodyMudit** [comment]
Can I merge the PR if it is not an issue?

**Comment by jettero** [comment]
Indeed. I recommended an admin merge in Slack. I don't understand why there's no way for admin's to clear a spurious check-block.

**Pull request merged**
