### PR TITLE
Forward Controlled to Splunk.

### PR DESCRIPTION
**Pull request by rbthomp**
Send Controlled results to Splunk along with Success and Failed.

### CODE REVIEW

**Comment by basepi** [comment]
You can see that we already have two mostly-duplicated code blocks: https://github.com/hubblestack/hubble/blob/04a4836cbafeb66439d66bd9115de0a334f30066/hubblestack/extmods/returners/splunk_nova_return.py#L114-L208

@rbthomp is just adding a third for "Controlled" events, which seems reasonable to me. Shouldn't affect any of the Adobe stuff since we don't Control checks, we just report everything and decide what we care about in Splunk.

**Comment by rbthomp** [comment]
@basepi We are making use of setting Control items and needed a way to get "controlled" items into splunk. I know that there is alot of code reuse going on here, but without refactoring the whole returner I just copied the mechanisms already used for Failed and Success.

**Comment by basepi** [comment]
No problem. I was just explaining for @jettero's benefit.

**Comment by praksinha** [comment]
Seems good to me. I agree with @basepi that it shouldn't impact Adobe's workflows.
Having said that, there's definitely scope for refactoring here as we have multiple copies of same code.

@rbthomp Please accept the Adobe CLA. Once you accept and there are no further comments, we'll get this merged.

**Comment by fossam** [comment]
@rbthomp other than the CLA, it's ready for merge.

**Comment by jettero** [comment]
I'm not convinced we need this and the author abandoned the PR in any case. I'm going to close it for now. We can always re-open it if we decide we need it, but it's been a half a year -- we don't seem to need it.

**Pull request closed without merging**
