### PR TITLE
Apaliwal/add misc functions

### PR DESCRIPTION
**Pull request by anuragpaliwal80**
PLEASE DO NOT MERGE IT FOR NOW.

### CODE REVIEW

**Comment by anuragpaliwal80** [comment]
@basepi Can you please review and let me know if this is correct way to implement checks in misc file ?

**Comment by basepi** [comment]
This looks pretty good -- however, instead of re-implementing shell commands, can you use `__salt__['cmd.run']()` instead? I think there are examples in the other nova modules. We have access to all the salt modules so there's no need to reinvent the wheel.

**Comment by basepi** [comment]
Also, it looks like in https://github.com/hubblestack/hubblestack_data/pull/26 you're not actually passing in a reason. In that case, if the function doesn't need any arguments, you can just have it take zero arguments.

**Comment by anuragpaliwal80** [comment]
Got it. Sure let me try with __salt__['cmd.run'](). Thanks for the direction.

**Comment by anuragpaliwal80** [comment]
If any checks fails and we want to return the reason, we can use first argument to return failure with reason. I referred:
`def test_failure_reason(reason):
    '''
    Automatically returns failure, with a reason (first arg)
    '''
    return reason`
That's the reason why I have passed blank arg so that we can show the failures to the users. Like
` 'Failure': [{'CIS-5.2.4': {'args': [''],
                            'description': 'Ensure system accounts are non-login',
                            'failure_reason': 'zabbix:x:498:497::/home/zabbix:/bin/bash',
                            'function': 'system_account_non_login',
                            'module': 'misc',
                            'nova_profile': 'misc',
                            'tag': 'CIS-5.2.4'}}],`

**Comment by basepi** [comment]
Right, I just noticed you weren't using the reason in your other pull request, so I wanted to be clear that it's optional.

In fact, we could give it a default, like `reason=''` or something, that way you could leave off the reason rather than passing in an empty string.

**Comment by anuragpaliwal80** [comment]
Sure. Got it.

**Comment by mew1033** [comment]
A handful of these could be solved with an awk nova module. @fossam and I have been talking about it for a while now.

**Comment by anuragpaliwal80** [comment]
@mew1033 Can you please share the PR for the same so that I can have a look? I am not able to see awk nova module. -thanks

**Comment by mew1033** [comment]
No PR for it yet. We've just talked about the idea.

**Comment by anuragpaliwal80** [comment]
Oh ok. Got it.

**Comment by anuragpaliwal80** [comment]
@basepi We are done for this sprint, please review and merge the changes (if all is ok). FYI... We will be adding more checks in coming sprint and hence will start new PR for the same.

**Pull request merged**
