### PR TITLE
Empty audit issue

### PR DESCRIPTION
**Pull request by jettero**
This took a sec to track down. I assumed at first it must be a problem with the data_list, but that was spurious -- I did leave some tuning in there anyway, but it's harmless.

The real problem was that since the dunder nova dict is a proper lazy loader and not a kludged loader, accessing the cache in the property under-dict is spurious now. The correct way is to iterate the items and keys of the dictionary itself.

### CODE REVIEW

**Comment by goravsingal** [comment]
@jettero This is also not working. 

I ran hubble.audit and got following error: (last lines of log)

06:53:17 [INFO ] Client-Request-ID=a9313b4c-e1e8-11ea-9b37-0242ac110002 Outgoing request: Method=GET, Path=/hubblestackdata/ndtrack/ndtrack_win_args, Query={'snapshot': None, 'timeout': None, 'sv': '2017-04-17', 'si': 'prod_locb_rl_policy', 'sr': 'c', 'sig': 'REDACTED'}, Headers={'x-ms-lease-id': None, 'If-Modified-Since': None, 'If-Unmodified-Since': None, 'If-Match': None, 'If-None-Match': None, 'x-ms-range': 'bytes=0-33554431', 'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.6.10; Linux 4.19.76-linuxkit)', 'x-ms-client-request-id': 'a9313b4c-e1e8-11ea-9b37-0242ac110002', 'x-ms-date': 'Wed, 19 Aug 2020 06:53:17 GMT'}.
06:53:17 [INFO ] Client-Request-ID=a9313b4c-e1e8-11ea-9b37-0242ac110002 Receiving Response: Server-Timestamp=Wed, 19 Aug 2020 06:53:17 GMT, Server-Request-ID=662732bc-301e-00be-39f5-75fbcd000000, HTTP Status Code=206, Message=Partial Content, Headers={'content-length': '606', 'content-type': 'application/octet-stream', 'content-range': 'bytes 0-605/606', 'last-modified': 'Mon, 21 Oct 2019 08:42:18 GMT', 'accept-ranges': 'bytes', 'etag': '"0x8D7560295068A73"', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '662732bc-301e-00be-39f5-75fbcd000000', 'x-ms-client-request-id': 'a9313b4c-e1e8-11ea-9b37-0242ac110002', 'x-ms-version': '2019-02-02', 'x-ms-creation-time': 'Mon, 21 Oct 2019 08:42:18 GMT', 'x-ms-blob-content-md5': 'fcWvzhqRY+TQ7cfKKBTuwQ==', 'x-ms-lease-status': 'unlocked', 'x-ms-lease-state': 'available', 'x-ms-blob-type': 'BlockBlob', 'x-ms-server-encrypted': 'true', 'date': 'Wed, 19 Aug 2020 06:53:17 GMT'}.
06:53:17 [INFO ] Executing user-requested function hubble.audit
06:53:17 [ERROR] Failed to import module hubble, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/hubble_build/hubblestack/loader.py", line 869, in _load_module
    mod = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/hubble_build/hubblestack/extmods/modules/hubble.py", line 674
    ret = {'loaded': list(__nova__)),
                                   ^
SyntaxError: invalid syntax
06:53:26 [ERROR] Function hubble.audit is not available, or not valid.

**Comment by goravsingal** [comment]
This is taking much longer than I expected. And, this issue remains there from last few commits.
Can you please test your code by running "hubble.audit" before pushing a commit.

**Comment by jettero** [comment]
It definitely worked for me by simply running `hubble -vvv hubble.audit`

```

**Comment by jettero** [comment]
My hunch is that you need to `git clean` or use the right python version or something, but without further information, it's hard to guess.

**Comment by jettero** [comment]
No, on second thought, some minor typo worked its way in before I pushed to github I guess.

**Review by goravsingal — APPROVED** [review]

**Pull request merged**
